# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

In [182]:
import numpy as np

### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [183]:
arr = np.array([np.arange(10,80,5),np.arange(5,47,3)]) #itself an array
print('Created array is: ',('\n') ,arr)

Created array is:  
 [[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

In [184]:
c5 = arr[:,4]
c7 = arr[:,6]
c11 = arr[:,10]
print(('\n'),
    'column 5 is: ', c5, ('\n'),
    'column 7 is:  ', c7, ('\n'),
    'column 11 is: ', c11)


 column 5 is:  [30 17] 
 column 7 is:   [40 23] 
 column 11 is:  [60 35]


### Select the 2nd row and fourth-last to second-last columns

In [185]:
r2 = arr[1,-4:-1]
print('fourth last to second last column is 2nd row:', r2)

fourth last to second last column is 2nd row: [35 38 41]


### Select 3rd to 3rd last columns skipping every second column

In [186]:
slic = arr[:,2:-2:2]
print(slic)

[[20 30 40 50 60]
 [11 17 23 29 35]]


###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [187]:
slic = arr[:,2:-2:2]
slic = np.flip(slic, axis=1 ) #if we don't spcify the axis it flips the array in all axis
print(slic)

[[60 50 40 30 20]
 [35 29 23 17 11]]


### We will work with the following array:

In [188]:
a = np.arange(25).reshape(5, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Use slicing only to select 3rd and last row along with 2nd and last columns

In [189]:
print(a[2::2,1::3])

[[11 14]
 [21 24]]


### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [190]:
slic = a[::2,2:4]
print(slic)

[[ 2  3]
 [12 13]
 [22 23]]


### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [191]:
a = np.arange(25).reshape(5, 5)
# print(a)
indices = [1,3]
slic = a[[1,3,4],1::2]
# slic = a[[1,3,4]][:,[1,2,4]]
print(slic)


[[ 6  8]
 [16 18]
 [21 23]]


### Change the values 1, 10, 19 and 22 in the array to -2

In [192]:
a = np.arange(25).reshape(5, 5)

a[(0,2,3,4),(1,0,-1,2)] = -2
print(a)

[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Repeat above using boolean indexing

In [193]:
a = np.arange(25).reshape(5,5)

# creating bool array
b = np.zeros((5,5), dtype='bool')
b[(0,2,3,4),(1,0,-1,2)] = 1

a[b] = -2
print(a)



[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [194]:
a = np.arange(25).reshape(5,5)
# print(a)

# simple way
print(a[[0,2,3],::3])

# creating bool array
b = np.zeros((5,5), dtype='bool')
b[[0,2,3],::3] = 1
# print('boolean indices are: ',('\n'), b)

# print(a[b])




[[ 0  3]
 [10 13]
 [15 18]]


### Calculating the sum, min and max of all diagonal values

In [195]:
a = np.arange(25).reshape(5,5)
# print(a)

# extracting diagnol values
print(a[[0,1,2,3,4],[0,1,2,3,4]])

#claculating sum
print('sum of diagnol values is: ', np.sum(a[[0,1,2,3,4],[0,1,2,3,4]]))

#claculating min
print('min of diagnol values is: ', np.min(a[[0,1,2,3,4],[0,1,2,3,4]]))

#claculating max
print('max of diagnol values is: ', np.max(a[[0,1,2,3,4],[0,1,2,3,4]]))

[ 0  6 12 18 24]
sum of diagnol values is:  60
min of diagnol values is:  0
max of diagnol values is:  24


### Calculate the sum of differences between the 2nd row and 2nd last column

In [196]:
a = np.arange(25).reshape(5,5)
# print(a)

#extracting 2nd row
b = a[1]
# print(b)

#extracting 2nd colomn
c = a[:,-1]
# print(c)

# differences between 2nd row and colomn
d = b - c
# print(d)

# sum of differences
e = np.add.reduce(d)
print(e)

-35


### Create a new array that is the sum of even rows and odd rows

In [197]:
a = np.arange(25).reshape(5,5)
# print(a)

# extraction of even rows
evenrows = a[1::2]
# print(evenrows)

# Extraction of odd rows
oddrows = a[0::1]

# Array based on sum of even rows
evenarr = np.add.reduce(evenrows)
print(evenarr)

# Array based on sum of odd rows
oddarr = np.add.reduce(oddrows)
print(oddarr)

[20 22 24 26 28]
[50 55 60 65 70]


## You are done. Good job!