In [1]:
import numpy as np

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [2]:
#list creation
list = [1,2,3,4,5,6,7,8,9,10]

# Type
Accuire type of list in python.

In [3]:
print('type: ', type(list))

type:  <class 'list'>


# Creatation of Arrays
1.SIMPLE ARRAY CREATION

2.CHECKING THE TYPE

3.NUMERIC "TYPE" OF ELEMENTS OF ARRAYS

4.Array dim

5.Array Shape

6.BYTES PER ELEMENT

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [4]:
# 1.SIMPLE ARRAY CREATION
print('-----------1-----------')
arr = np.array([1,2,3,4,5])
print('simple array: ', arr)
print()

print('-----------2-----------')
# 2.CHECKING THE TYPE
print('type of the array: ', type(arr))
print()

print('-----------3-----------')
# 3.NUMERIC "TYPE" OF ELEMENTS OF ARRAYS
print('type of elements of array: ', arr.dtype)
print()

print('-----------4-----------')
# 4.Array dim
print('dimensions of array: ', arr.ndim)
print()

print('-----------5-----------')
# 5.Array Shape
print('shape of the array: ', arr.shape)
print()

print('-----------6-----------')
# 6.BYTES PER ELEMENT
print('bytes per element: ', arr.nbytes)
print()

print('-----------7-----------')
# 7.BYTES OF MEMORY USED, How many bytes for one array element
print('bytes for one array element: ', arr.itemsize )
print()

print('-----------8-----------')
# 8.Total bytes in an Array
# Total bytes = Number of elements × Bytes per element
print('Total bytes: ', len(arr)*arr.itemsize )
print()

-----------1-----------
simple array:  [1 2 3 4 5]

-----------2-----------
type of the array:  <class 'numpy.ndarray'>

-----------3-----------
type of elements of array:  int32

-----------4-----------
dimensions of array:  1

-----------5-----------
shape of the array:  (5,)

-----------6-----------
bytes per element:  20

-----------7-----------
bytes for one array element:  4

-----------8-----------
Total bytes:  20



In [5]:
print('----------1----------')
# 1.SIMPLE ARRAY CREATION
darr = np.arange(0.1,5.1,0.5)
print('decimal array: ', darr)
print()

print('----------2----------')
# 2.CHECKING THE TYPE
print('type of the array: ', type(darr))
print()

print('----------3----------')
# 3.NUMERIC "TYPE" OF ELEMENTS OF ARRAYS
print('type of elements of arrays: ', darr.dtype)
print()

print('----------4----------')
# 4.Array dim
print('dimensions of array: ', darr.ndim)
print()

print('----------5----------')
# 5.Array Shape
print('shape of the array: ', darr.shape)
print()

print('----------6----------')
# 6.BYTES PER ELEMENT
print('bytes per element: ', darr.nbytes)
print()

print('----------7----------')
# 7.BYTES OF MEMORY USED, How many bytes for one array element
print('bytes for one array element: ', darr.itemsize )
print()

print('----------8----------')
# 8.Total bytes in an Array
# Total bytes = Number of elements×Bytes per element
print('Total bytes: ', len(darr)*darr.itemsize )
print()


----------1----------
decimal array:  [0.1 0.6 1.1 1.6 2.1 2.6 3.1 3.6 4.1 4.6]

----------2----------
type of the array:  <class 'numpy.ndarray'>

----------3----------
type of elements of arrays:  float64

----------4----------
dimensions of array:  1

----------5----------
shape of the array:  (10,)

----------6----------
bytes per element:  80

----------7----------
bytes for one array element:  8

----------8----------
Total bytes:  80



9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


In [6]:
arr1 = np.arange(1,10,2, dtype='int32')
print('initial int32 type array:', arr1)
print()

print('----------9,10----------')
arr1[2] = 11.3
arr1.fill(3.1) #fill func modifies the array
print('after assigning a float:', arr1)
print('data type after asignment: ', arr1.dtype)

# # Learning: data type remains same utill and unless you explicitly changes it. 'astype'
# # for practice
# arr1[:] = "11.1"
# print(arr1)

initial int32 type array: [1 3 5 7 9]

----------9,10----------
after assigning a float: [3 3 3 3 3]
data type after asignment:  int32


11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function tocreate an array with step of from 1.0 to 3.0

In [7]:
arr1 = np.arange(0,10,2)
arr2 = np.arange(1,10,2)
print('Array 1 is: ', arr1)
print('Array 2 is: ', arr2)
print()

print('------------11-----------')
print('sum of the 2 arrays is: ', arr1+arr2)
print()

print('------------12-----------')
print('product of the 2 arrays is: ', arr1*arr2)
print()

print('------------13-----------')
print('Using ** operator: ', arr1**2)
print()

print('------------14-----------')
# Create array from 0.0 to 11.0
arr3 = np.arange(0.0,12.0)
print('Array from 0.0 to 11.0 is: ', arr3)
print()

print('------------15-----------')
# scalar value:
c= 2.0*np.pi
print('Multiplication with scalar value', arr2*c)
print()

print('------------16-----------')
arr = np.arange(1.0,10.0,2.0)
print('array creation with np.arange and steps of 1.0 to 3.0: ', arr)
print()


Array 1 is:  [0 2 4 6 8]
Array 2 is:  [1 3 5 7 9]

------------11-----------
sum of the 2 arrays is:  [ 1  5  9 13 17]

------------12-----------
product of the 2 arrays is:  [ 0  6 20 42 72]

------------13-----------
Using ** operator:  [ 0  4 16 36 64]

------------14-----------
Array from 0.0 to 11.0 is:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

------------15-----------
Multiplication with scalar value [ 6.28318531 18.84955592 31.41592654 43.98229715 56.54866776]

------------16-----------
array creation with np.arange and steps of 1.0 to 3.0:  [1. 3. 5. 7. 9.]



# Slicing
var[lower:upper:step]
- Extracts a portion of a sequence by specifying a lower and upper bound.

- The lower-bound element is included, but the upper-bound element is not included.

- Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8. Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [8]:
arr = np.arange(0,20,2)
print('Initial array is: ', arr)
# print(len(arr))
print()

print('----------1----------')
arr1 = arr[1:4]
print('indices from 1 to 3 have: ', arr1) 
print()

print('----------2----------')
arr2 = arr[-9:-6]
print('same indices with neg indexing: ', arr2)
print()

print('----------3----------')
arr3 = arr[:3]
print('first three elements are: ', arr3)
print()

print('----------4----------')
arr4 = arr[-2:]
print('last two elements are: ', arr4)
print()

print('----------5----------')
arr5 = arr[::2]
print('every other element is: ', arr5 )
print()

print('----------6----------')
arr6 = arr[-2:]
print('last two elements are: ', arr6)
print()

print('----------7----------')
arr7 = np.array([1,2,3,4,5])
print('initial array: ', arr7)
i = [11,12]
arr7[3:]= i
# Yes we can insert an iterable but can not change the shape of the array.
arr7[0] = 0
print('modified array after insertion of an iterable and scalar: ', arr7)
print()

print('----------8----------')
a = np.array([1,2,3,4,5])
print('initial array: ', a)
b = a[1::2]
print('slice is: ', b)
b[0]= 3
print('modified b: ', b)
print('modified a wrt b: ', a)
print()

print('----------9----------')
a = np.array([[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]])
print(a)
# values from row 3 to onwards
# r3 = a[2,:]
# print(r3) # output: index 2 is out of bounds for axis 0 with size 2
# values from col 0, 2 and 5
c0 = a[0:,0]
c2 = a[0:,2]
c5 = a[0:,4]
print('values from col 0, 2 and 5 are: ', c0, c2, c5)
print()

Initial array is:  [ 0  2  4  6  8 10 12 14 16 18]

----------1----------
indices from 1 to 3 have:  [2 4 6]

----------2----------
same indices with neg indexing:  [2 4 6]

----------3----------
first three elements are:  [0 2 4]

----------4----------
last two elements are:  [16 18]

----------5----------
every other element is:  [ 0  4  8 12 16]

----------6----------
last two elements are:  [16 18]

----------7----------
initial array:  [1 2 3 4 5]
modified array after insertion of an iterable and scalar:  [ 0  2  3 11 12]

----------8----------
initial array:  [1 2 3 4 5]
slice is:  [2 4]
modified b:  [3 4]
modified a wrt b:  [1 3 3 4 5]

----------9----------
[[0 1 2 3 4]
 [1 2 3 4 5]]
values from col 0, 2 and 5 are:  [0 1] [2 3] [4 5]



# Array Functions
1.Arange([start,] stop[, step],dtype=None) 
Nearly identical to Python’s range(). 
Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


In [9]:
print('--------1--------')
arr = np.arange(0, 30, 3)
print('array created with arange is: ', arr)
print()

print('--------2--------')
# with ones
print('array with ones: ')
arr = np.ones((5,5))
print(arr)
# print(arr.dtype)
# with zeors
print('array with zeros: ')
arr = np.zeros((5,5))
print(arr)
# print(arr.dtype)
print()

print('--------3--------')
print('identity matrix: ')
iarr = np.identity(5)
print(iarr)
print()

print('--------4--------')
arr = np.empty((5,5))
arr.fill(3)
print('array using empty and fill func', arr)
# using full
arr = np.full((5,5), 3)
print('array with full function: ', arr)
#linspace
arr = np.linspace(1,10, 20)
print('array using linspace: ', ('\n'), arr)
# min
print('min: ', arr.min())
# max
print('max: ', arr.max())
# argmax
print('argmax: ', arr.argmax())
# mean
print('mean: ', arr.mean())
# var
print('var: ', arr.var())
# std
print('std: ', arr.std())


print()

# print('--------5--------')

# print()

print('--------6--------')
arr = np.arange(-15,15).reshape(5,6)**2
# print(arr)
#The maximum of each row
print('maximum of each row is: ', arr.max(axis=1))

#The mean of each column
print('mean of each row is: ', arr.mean(axis=1)) 

#The position of overall minimum
print('position of overall min is: ', arr.argmin())
print()


--------1--------
array created with arange is:  [ 0  3  6  9 12 15 18 21 24 27]

--------2--------
array with ones: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
array with zeros: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

--------3--------
identity matrix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

--------4--------
array using empty and fill func [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
array with full function:  [[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
array using linspace:  
 [ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
min:  1.0
max:  10.0
argmax:  19
mean:  5.5
var:

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [10]:
print('-------ZIP FUNCTION ON TWO ARRAYS------')
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]
arra = np.array(a)
arrb = np.array(b)
print('Two arrays are: ', ('\n'), arra, ('\n'), arrb )
print()

ab = zip(arra, arrb)
print(ab)
print()

print('------ARRAY WITH SUM With FOR LOOP-------')
listofsum = []
for x , y  in ab :
    # print(x, y)
    sum = x+y
    listofsum.append(sum)

# print(listofsum)
arr = np.array(listofsum)
print(arr)
# print(arr)
# print(type(i))


-------ZIP FUNCTION ON TWO ARRAYS------
Two arrays are:  
 [1 2 3 4] 
 [2 3 4 5]


------ARRAY WITH SUM With FOR LOOP-------
[3 5 7 9]


# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING


In [11]:
arr1 = np.random.randint(10, size=(4,3))
# print(arr1)

arr2 = np.random.randint(10, size=(1,3))
# print(arr2)

arr3 = arr1 + arr2
print('Array after broadcasting is: ', ('\n'), arr3)

Array after broadcasting is:  
 [[ 5  5 10]
 [10  5 15]
 [ 8  3 10]
 [11  9 17]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [12]:
print('-----------1----------')
arr = np.arange(0,10,2)
print('sum of array after reduce operation: ', np.add.reduce(arr))
print()

print('-----------2----------')
print('sum of array with accumulate operation: ', np.add.accumulate(arr))


-----------1----------
sum of array after reduce operation:  20

-----------2----------
sum of array with accumulate operation:  [ 0  2  6 12 20]
