In [2]:
import numpy as np

In [3]:
# from google.colab import drive
# drive.mount('/content/drive')

# Q.1
**Statement:** You are working with a retail store that needs to manage its inventory efficiently. They have provided you with a dataset containing information about products, their quantities in stock, and the number of units sold daily for the past week. Total number of products are 5. Your task is to calculate the following:



1.The total sales for each product over the past week.

2.The average daily sales for each product.

3.The product with the highest sales.

4.The product with the lowest sales.

5.The total sales for all products combined.

You are required to use NumPy for efficient data processing and calculations. Write code to solve this inventory management problem.

In [4]:
# Sample data (replace with your actual data)
#product names:
products = np.array(['Product A', 'Product B', 'Product C', 'Product D', 'Product E'])

# Quantities in stock for the past week (in units)
stock_quantities = np.array([
    [150, 145, 140, 135, 130, 125, 120],  # Product A
    [180, 175, 170, 165, 160, 155, 150],  # Product B
    [120, 115, 110, 105, 100, 95, 90],    # Product C
    [200, 195, 190, 185, 180, 175, 170],  # Product D
    [160, 155, 150, 145, 140, 135, 130]   # Product E
])

# Units sold for the past week (daily sales) (in units)
units_sold = np.array([
    [25, 28, 30, 27, 32, 29, 31],  # Product A
    [20, 22, 24, 21, 23, 26, 25],  # Product B
    [18, 20, 17, 19, 16, 21, 20],  # Product C
    [30, 31, 29, 28, 33, 32, 34],  # Product D
    [22, 24, 26, 23, 27, 25, 28]   # Product E
])

# Display the arrays
# print('Products: ' ,('\n'), products)
# print('Stock Quantities (Units)', ('\n'), stock_quantities)
# print('Units Sold (Daily Sales) (Units): ', ('\n'), units_sold)

# Calculate total sales revenue for each product over the past week
total_sales = np.sum(units_sold, axis=1)
print('total sales revenue for each product over the past week:', ('\n'), total_sales)
print()

# Calculate average daily sales for each product
average_daily_sale = np.mean(units_sold, axis=1)
print('average daily sales for each product:', ('\n'), average_daily_sale)
print()

# Find the product with the highest and lowest sales
# highest sale:
# finding the highest sale of products:
highest_sales = np.max(units_sold, axis=1)
# print('highest sales of each product:', ('\n'), highest_sales)

# finding the index for product with highest sale
highest_sale_value = np.max(highest_sales)
highest_index = np.argmax(highest_sales)
highest_sale_product = products[highest_index]
print(f'{highest_sale_product} is the product with highest {highest_sale_value} sales')

#lowest sale:
# finding the lowest sale of products:
lowest_sales = np.max(units_sold, axis=1)
# print('lowest sales of each product:', ('\n'), lowest_sales)

# finding the index for product with lowest sale
lowest_sale_value = np.min(lowest_sales)
lowest_index = np.argmin(lowest_sales)
lowest_sale_product = products[lowest_index]
print(f'{lowest_sale_product} is the product with lowest {lowest_sale_value} sales')
print()

# Calculate the total sales revenue for all products combined
total_sales = np.sum(units_sold, axis=(0,1))
print('total sales revenue for all products combined:', ('\n'), total_sales)
print()


total sales revenue for each product over the past week: 
 [202 161 131 217 175]

average daily sales for each product: 
 [28.85714286 23.         18.71428571 31.         25.        ]

Product D is the product with highest 34 sales
Product C is the product with lowest 21 sales

total sales revenue for all products combined: 
 886



# Q.2
**Statement:** Statement: You are working with a manufacturing plant that produces various components. They have provided you with data on the production rates of five different machines over the past month. Your task is to analyze the performance of these machines by calculating the following metrics:

1.The total production output for each machine over the past month.

2.The average daily production rate for each machine.

3.The machine with the highest total production output.

4.The machine with the lowest total production output.

5.The overall production efficiency of the plant, which is defined as the ratio of the total production output to the total number of hours worked, and working hour for each day is 2 hours.

In [5]:
# Sample data (replace with your actual data)
# undestanding the data generation requirements: (5 diff plants : 30 days of month)
# Generate random production rates between 100 and 200 for 5 machines and 30 days

production_rates = np.random.randint(100,200, size=(5,30))
print('Production Rates: ', ('\n'), production_rates)
# print(production_rates.shape)
print()

# Calculate total production output for each machine over the past month
total_production_per_machine = np.sum(production_rates, axis=1)
print('total production output for each machine over the past month:', ('\n'), total_production_per_machine)
print()

# Calculate average daily production rate for each machine
avg_daily_production = np.mean(production_rates, axis=1)
print('average daily production rate for each machine: ', ('\n'), avg_daily_production)
print()

# Find the machine with the highest and lowest total production output
highest_machine_index = np.argmax(total_production_per_machine)
lowest_machine_index = np.argmin(total_production_per_machine)
print('Machine with the highest total production output:', highest_machine_index)
print('Machine with the lowest total production output:', lowest_machine_index)
print()

# Calculate the overall production efficiency of the plant
# ratio of the total production output to the total number of hours worked, 
# and working hour for each day is 2 hours 
total_production = np.sum(total_production_per_machine)
working_hours = 2 * 30  #2 hours a month 
production_efficiency = total_production / working_hours
print('the overall production efficiency of the plant:', production_efficiency)
print()

Production Rates:  
 [[147 185 134 184 172 190 102 177 105 134 188 181 124 113 137 135 123 103
  129 104 160 137 140 181 107 194 157 142 123 199]
 [175 184 164 189 160 170 162 138 133 142 175 110 129 127 103 100 183 149
  151 181 198 187 168 165 103 166 179 145 127 139]
 [177 198 110 154 171 176 168 162 120 155 192 113 111 149 155 195 101 175
  192 166 123 172 187 158 178 168 114 137 167 119]
 [159 135 182 143 177 109 185 165 140 136 122 161 145 167 167 158 111 133
  179 144 158 107 145 158 189 120 187 107 153 175]
 [132 179 173 178 154 117 157 168 124 133 126 190 160 162 127 153 172 127
  167 153 162 110 125 181 118 166 112 177 197 108]]

total production output for each machine over the past month: 
 [4407 4602 4663 4517 4508]

average daily production rate for each machine:  
 [146.9        153.4        155.43333333 150.56666667 150.26666667]

Machine with the highest total production output: 2
Machine with the lowest total production output: 0

the overall production efficiency of 

# Q3:

**Statment**
You are working on a project that involves simulating sensor data for a network of 10 sensors over a period of 15 days. Each sensor collects data once per hour. Your task is to generate a NumPy array named sensor_data to represent this simulated sensor data and perform following statistical analysis on it.

Populate the sensor_data array with random floating-point values between 0.0 and 100.0
The generated values should represent sensor readings collected once per hour.

After generating the sensor_data array, perform the following statistical **calculations:**

1.Calculate the mean (average) sensor reading for each sensor over the 15 days.

2.Calculate the standard deviation of sensor readings for each sensor.

3.Calculate the maximum sensor reading for each sensor.

4.Calculate the minimum sensor reading for each sensor.

5.Calculate the overall mean sensor reading for all sensors and all days.

6.Calculate the overall standard deviation of sensor readings for all sensors an

In [6]:
# Data Generation Requirements
num_sensors = 10
num_days = 15
hours_per_day = 24
shape = (num_sensors, num_days * hours_per_day)

# creating sensor data array:
sensor_data = np.random.uniform(0.0,100.0, size=shape)
# displaying array:
print('sensor readings collected once per hour: ', sensor_data)
print(sensor_data.shape)
print()

# Calculate the mean (average) sensor reading for each sensor over the 15 days.
avg_sensor_reading = np.mean(sensor_data, axis=1)
print('the mean (average) sensor reading for each sensor over the 15 days: ', avg_sensor_reading)
print()

# Calculate the standard deviation of sensor readings for each sensor.
std_sensor_reading = np.std(sensor_data, axis=1)
print('the standard deviation of sensor readings for each sensor: ', std_sensor_reading)
print()

# Calculate the maximum sensor reading for each sensor.
max_sensor_reading = np.max(sensor_data, axis=1)
print('the maximum sensor reading for each sensor: ', max_sensor_reading)
print()

# Calculate the minimum sensor reading for each sensor.
min_sensor_reading = np.min(sensor_data, axis=1)
print('the minimum sensor reading for each sensor: ', min_sensor_reading)
print()

# Calculate the overall mean sensor reading for all sensors and all days.
all_sensor_readings = np.sum(sensor_data, axis=(1))
overall_mean_sensor_reading = np.mean(all_sensor_readings)
print('the overall mean sensor reading for all sensors and all days: ', overall_mean_sensor_reading)
print()

# Calculate the overall standard deviation of sensor readings for all sensors
overall_std_sensor_reading = np.std(all_sensor_readings)
print('the overall standard deviation of sensor readings for all sensors: ', overall_std_sensor_reading)
print()


sensor readings collected once per hour:  [[75.41564789 72.08398688 41.26797831 ... 30.49980885 99.40546364
  59.67361226]
 [28.51048722 70.6681819  93.35248091 ... 96.40121177 99.06432054
  44.0207437 ]
 [25.79590133 13.77365149 13.84297685 ... 93.17936077 65.91492724
  96.97493219]
 ...
 [ 4.78490201 25.85184721 69.31262541 ...  4.72039481 38.58464871
  40.07974731]
 [87.57241289  2.57450794 82.98295627 ... 84.76391335 19.3057811
  30.7934917 ]
 [74.70192123 87.58327725 65.1024763  ... 82.80974675 85.53198714
  61.71750551]]
(10, 360)

the mean (average) sensor reading for each sensor over the 15 days:  [49.78515305 49.81149868 50.14750474 52.08431166 51.63810969 50.48579824
 47.63647926 48.92019008 49.78808029 52.41467854]

the standard deviation of sensor readings for each sensor:  [29.28555874 28.05881023 28.62393341 29.65159624 28.50521463 27.5352748
 29.17185253 29.45540544 28.95070608 29.26738321]

the maximum sensor reading for each sensor:  [99.42942636 99.76363203 99.6233578

# Q4:

**Statement**: You are tasked with analyzing the exam scores of 30 students in a class over a period of 10 exams. The exam scores are represented as a NumPy, where each row corresponds to a different student, and each column represents their score in a specific exam.

Populate the exam_scores array with random integer values between 50 and 100 to simulate students' exam performance.

After generating the exam_scores array, perform the following tasks:

1.Calculate the average score for each student over the 10 exams.

2.Calculate the standard deviation of scores for each student.

3.Identify students who have consistently performed well, defined as those whose average score is above 85.

4.Identify students who may need additional support, defined as those whose average score is below 50.

Write code to create and populate the exam_scores array and then perform the specified statistical analysis and performance evaluation tasks on the data.





In [7]:
# Create the exam_scores array (30 students, 10 exams)
num_students = 30
num_exams = 10
shape = (num_students, num_exams)

# Populate the exam_scores array with random scores between 50 and 100
exam_scores = np.random.randint(50,100, size= shape)
# displaying array:
print('exam_scores array: ', ('\n'), exam_scores)
# print(exam_scores.shape)
print()

# 1. Calculate the average score for each student over the 10 exams
avg_score_per_student = np.mean(exam_scores, axis=1)
print('the average score for each student over the 10 exams: ', ('\n'), avg_score_per_student)
print()

# 2. Calculate the standard deviation of scores for each student
std_per_student = np.std(exam_scores, axis=1)
print('the standard deviation of scores for each student: ', ('\n'), std_per_student)
print()

# 3. Identify students who have consistently performed well (average score > 85)
well_performed_students = np.where(avg_score_per_student>85)[0] # might be empty if no students fall in this catagory
print('students who have consistently performed well: ', well_performed_students)
print()

# 4. Identify students who may need additional support (average score < 60)
students_need_support = np.where(avg_score_per_student<60)[0] # might be empty if no students fall in this catagory
print('students who may need additional support: ', students_need_support)
print()

exam_scores array:  
 [[88 60 93 56 61 50 69 50 91 60]
 [88 60 66 71 93 96 83 72 52 93]
 [88 78 86 64 50 91 56 90 79 55]
 [52 51 83 95 72 95 84 82 62 68]
 [62 84 76 53 94 66 63 78 58 92]
 [53 57 66 83 75 76 85 50 50 80]
 [53 56 79 65 65 86 66 91 90 51]
 [94 84 58 65 87 60 99 65 52 82]
 [53 81 82 68 63 91 52 79 55 54]
 [85 68 78 61 85 79 62 50 66 88]
 [55 72 97 95 88 55 64 64 95 87]
 [73 64 63 85 85 63 65 89 82 54]
 [86 61 67 79 51 70 96 69 71 68]
 [72 61 88 61 81 55 95 53 50 94]
 [95 73 92 56 82 57 57 74 54 93]
 [63 60 92 98 86 98 73 68 58 77]
 [65 70 86 89 89 93 81 76 89 91]
 [76 80 68 79 68 58 89 73 79 53]
 [71 67 53 66 80 83 75 66 85 94]
 [73 50 86 80 84 99 82 92 83 51]
 [56 53 98 50 87 85 95 91 93 59]
 [68 80 76 87 99 55 72 97 56 59]
 [61 95 56 56 60 53 84 54 75 72]
 [99 80 94 50 93 72 99 72 80 50]
 [67 75 88 80 62 87 87 82 50 78]
 [97 74 99 69 63 73 83 59 64 96]
 [72 67 64 78 58 72 51 50 81 64]
 [87 97 93 62 91 65 71 68 98 62]
 [63 56 91 99 83 70 97 96 51 84]
 [98 57 65 91 92 78 7