In [2]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [3]:
# creating a 3d array:
arr = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
# print(arr)
# print(arr.shape)

#sum of elements in array
s = np.add.reduce(arr)
# print(s)
s = np.add.reduce(s)
# print(s)
s = np.add.reduce(s)
print('Sum of all elements in array is: ', s)




Sum of all elements in array is:  60


# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [4]:
# creating array
arr = np.random.randint(0, 9, size=(2,3,4,5))
print(arr)

[[[[0 5 4 7 6]
   [6 6 4 1 5]
   [8 5 5 6 0]
   [5 7 0 6 1]]

  [[1 8 0 6 2]
   [3 0 3 0 3]
   [2 5 0 6 6]
   [2 2 2 5 3]]

  [[3 3 8 6 7]
   [5 6 4 2 5]
   [0 4 6 3 5]
   [5 4 1 8 1]]]


 [[[0 7 0 8 0]
   [7 4 1 3 8]
   [7 6 5 2 7]
   [2 8 6 0 8]]

  [[6 8 4 5 8]
   [2 8 7 6 7]
   [7 4 1 8 5]
   [0 1 1 8 2]]

  [[1 1 4 2 1]
   [8 1 6 2 6]
   [6 5 4 2 6]
   [4 6 6 3 4]]]]


# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [5]:
# creating array
arr = np.random.randint(0, 100, size=(2,3,4,5))
# print(arr)

mean = np.mean(arr, axis=1)
print('mean along 2nd axis is: ', mean)


mean along 2nd axis is:  [[[38.         59.66666667 20.33333333 13.33333333 25.33333333]
  [55.         36.66666667 63.         80.66666667 71.        ]
  [59.         80.66666667 41.33333333 46.66666667 54.66666667]
  [33.33333333 29.33333333 68.         48.66666667 36.66666667]]

 [[68.33333333 24.33333333 62.         63.         37.66666667]
  [48.         40.33333333 53.66666667 35.66666667 69.66666667]
  [48.66666667 53.         50.66666667 53.         29.        ]
  [27.66666667 24.         44.33333333 48.         53.66666667]]]


# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the mean temperature for each day.

Sample Input:

In [14]:
# creating array
arr = np.random.randint(15,45, size=(7,24,60))

# calculating mean
av = np.mean(arr, axis=0) #axis taken 0 beacuse we are calculating mean per day from dimensions
print(av)

[[25.71428571 31.42857143 27.14285714 ... 30.28571429 28.71428571
  29.        ]
 [32.14285714 34.28571429 28.14285714 ... 30.57142857 28.71428571
  34.28571429]
 [27.71428571 30.         33.57142857 ... 27.71428571 29.42857143
  28.85714286]
 ...
 [23.85714286 34.85714286 30.28571429 ... 28.42857143 28.28571429
  26.        ]
 [24.14285714 27.         34.14285714 ... 25.         28.14285714
  27.71428571]
 [29.14285714 32.57142857 29.         ... 34.         29.71428571
  32.57142857]]


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [7]:
# creating array
arr = np.random.randint(5,75, size=(4,7,24,60))

# calculating mean
mx = np.max(arr, axis=1) #axis taken 2 beacuse we are calculating max across all days from dimensions
print(mx)

[[[72 72 55 ... 65 66 69]
  [62 67 73 ... 74 74 74]
  [60 62 72 ... 70 62 74]
  ...
  [61 71 74 ... 64 71 54]
  [60 74 67 ... 67 58 72]
  [73 42 71 ... 60 73 64]]

 [[68 56 72 ... 69 69 63]
  [51 74 67 ... 70 64 73]
  [73 68 66 ... 65 68 71]
  ...
  [73 73 69 ... 68 69 72]
  [62 58 71 ... 66 68 72]
  [64 73 74 ... 74 72 74]]

 [[68 63 65 ... 72 59 63]
  [66 61 70 ... 71 73 65]
  [71 72 74 ... 65 68 73]
  ...
  [64 57 67 ... 72 57 60]
  [47 73 71 ... 45 70 52]
  [64 67 67 ... 52 65 57]]

 [[68 70 67 ... 72 62 69]
  [71 63 65 ... 68 71 72]
  [60 57 63 ... 63 66 66]
  ...
  [73 57 64 ... 61 67 49]
  [68 74 72 ... 62 72 57]
  [48 69 62 ... 64 73 68]]]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the mean length, width, and height across all objects.

Sample Inpumt:

In [8]:
# creating array
arr = np.random.randint(10,100, size=(100,50,3))

# calculating mean length
avlen = np.mean(arr[:,:,0])
print(avlen)

# calculating mean width
avwid = np.mean(arr[:,:,1])
print(avwid)

# calculating mean height
avhig = np.mean(arr[:,:,2])
print(avhig)

53.559
53.8436
54.123


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

mean measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [9]:
# according to problem statement: 
# 1d --- mulitiple(different) sensors - (axis 0)
# 2d --- different locations - (axis 1)
# 1d --- different time/period of time - (axis 2)
# so for each sensor operations will be performed along axis 1 and 2

#creating array first:
arr = np.random.randint(11,80, size=(5,6,7))
# print(arr)

# Total number of measurements for each sensor
total_measurements = np.sum(arr, axis=(1, 2))

# mean measurement value for each sensor
mean_measurement = np.mean(arr, axis=(1, 2))

# Standard deviation of measurements for each sensor
std_of_measuremnts = np.std(arr, axis=(1, 2))

# Minimum measurement value
min_measurement = np.min(arr, axis=(1, 2))

# Maximum measurement value
max_measurement = np.max(arr, axis=(1, 2))


print("Total number of measurements:", total_measurements)
print("mean measurement value:", mean_measurement)
print("Standard deviation of measurements:", std_of_measuremnts)
print("Minimum measurement value:", min_measurement)
print("Maximum measurement value:", max_measurement)

# Hence outpu shows 5 values because of 5 different sensors 
# yayyy!

Total number of measurements: [2067 1883 1928 1854 1957]
mean measurement value: [49.21428571 44.83333333 45.9047619  44.14285714 46.5952381 ]
Standard deviation of measurements: [19.77316088 18.24948358 20.87355301 18.54283513 18.5113344 ]
Minimum measurement value: [11 15 12 11 11]
Maximum measurement value: [79 78 79 78 78]


*For Understaning which axis is called with multidimensional arrays*

In [10]:
# arr1 = np.random.randint(1,10, size=(4,4))
# arr2 = np.random.randint(1,10, size=(2,4,4))
# arr3 = np.random.randint(1,10, size=(2,3,4,4))

In [11]:
# print(arr3)
# print(arr3.shape)

In [12]:
# print(np.sum(arr3, axis=2) )